name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      working-directory: front
      run: npm ci

    - name: Run tests and generate reports
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      working-directory: front

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image for frontend
      uses: docker/build-push-action@v2
      with:
        context: ./front
        file: ./front/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-image:latest

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build-and-deploy-frontend
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=org-shiirow-123
            -Dsonar.projectKey=shiirows_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
